In [1]:
# from openloop_walker.envs.gym.walk_env import RexWalkEnv
from openloop_walker.eval_envs.rex_gym_env import RexGymEnv
from stable_baselines3.common.env_util import make_vec_env

import numpy as np
from stable_baselines3 import PPO, SAC
import random


pybullet build time: May 20 2022 19:44:17


In [2]:
# env = RexWalkEnv(render=True, terrain_id='plane', signal_type='ol',terrain_type='plane', control_time_step=0.005, action_repeat=5, target_position=5, debug=True)
env = RexGymEnv(render=True, terrain_id='plane', signal_type='ol',terrain_type='plane', control_time_step=0.005, action_repeat=5, target_position=5, debug=True)

12
startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlopen/dlsym OK!
Creating context
Created GL 3.3 context
Direct GLX rendering context obtained
Making context current
GL_VENDOR=AMD
GL_RENDERER=AMD RENOIR (DRM 3.42.0, 5.15.0-56-generic, LLVM 12.0.0)
GL_VERSION=4.6 (Core Profile) Mesa 21.2.6
GL_SHADING_LANGUAGE_VERSION=4.60
pthread_getconcurrency()=0
Version = 4.6 (Core Profile) Mesa 21.2.6
Vendor = AMD
Renderer = AMD RENOIR (DRM 3.42.0, 5.15.0-56-generic, LLVM 12.0.0)
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started


/home/ros/.local/lib/python3.8/site-packages/gym/spaces/box.py:128: UserWarning: WARN: Box bound precision lowered by casting to float32
  logger.warn(f"Box bound precision lowered by casting to {self.dtype}")


ven = AMD


ven = AMD


In [357]:
actions = np.array([0,0,0,0,0,0,0,0,0,0,0,1])

In [358]:
print(len(actions))

12


In [370]:
obs, reward, done, info = env.step(action=actions)

[0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 1]


In [200]:
env.get_rex_motor_angles()

array([-9.27857794e-02,  8.88401862e-01,  3.52889853e-01, -2.81354704e-07,
        3.12047518e-09,  5.12670582e-09, -4.80567648e-10,  2.64147713e-09,
        8.50818126e-22, -1.30260483e-07, -1.50321290e-08,  1.63598191e-09])